### ISSUE TITLE
Logout icon in Administrator panel

### ISSUE THREAD

**Issue by Bositkhon** [Bositkhon/LibraryManagementSystemJavaFX#1]
@kaboomdev fix please

**Comment by kaboomdev** [comment]
![Screen Shot 2019-12-23 at 10 08 49 PM](https://user-images.githubusercontent.com/39704378/71370799-d8444700-25d0-11ea-978d-74b9fe46da25.png)

**Comment by kaboomdev** [comment]
dafuq maaaan
